config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root :to => 'home#home' 
  match '/special' => "home#special",via: [:get, :post]
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def home
	
end
def special
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_home2.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<body>
    <div id="header"></div>
    <div id="box1">
        <div class="logotext"> <span class="text">Example</span><span class="text2">.com</span>

            <p class="untertitel">Example</p>
        </div>
        <div class="buttons"> <a id="infobutton" href="#puffer" style="text-decoration: none; color: #FFFFFF;">Button Example</a>
 <a id="kontaktbutton" href="#puffer2" style="text-decoration: none; color: #FFFFFF;">Example</a>

        </div>
        <div id="puffer"></div>
    </div>
    <div id="box2"> <a id="navbutton" href="#box1" style="text-decoration: none; color: #FFFFFF;"><div class="dreieck"></div></a>

        <div id="puffer2"></div>
    </div>
    <div id="box3"> <a id="navbutton" href="#box1" style="text-decoration: none; color: #FFFFFF;"><div class="dreieck"></div></a>

    </div>
    <div class="footer">
        <div class="copyright"> <span style="margin: 0; color: #FFFFFF; float: left; margin-left: 20px; font-family: “cracked-johnnie”, sans-serif;">&copy; Example</span>
 <span style="margin: 0; color: #F58C1F; float: left; margin-left: 10px; font-family: “Exo”, sans-serif;">2014</span>
 <span style="margin: 0; color: #CCC; float: right; margin-right: 20px; font-family: “cracked-johnnie”, sans-serif; font-size: 25px; -moz-user-select: none; -khtml-user-select: none; cursor: default;">X</span>

        </div>
    </div>
</body>

</html>
<script type="text/javascript">
    $(document).ready(function() {
var fflag = true;
$(window).scroll(function() {

   var top = $(document).scrollTop();

   if (top > 30 && fflag) {
       fflag = false;
       $("#header").animate({height:50}, 200);
       $("#header").animate({opacity:0.5}, 200);
   }
    if (top<30 && !fflag){
       fflag=true;
       $("#header").animate({height:100}, 200);
       $("#header").animate({opacity:1}, 200);   
   }

})});

</script>
<style type="text/css">
    body {
    background: #FFFFFF;
    margin: 0;
}
@font-face {
    font-family: “Exo”;
    src: url(../schriften/Exo-ExtraLight.otf);
}
@font-face {
    font-family: “Exo-Fat”;
    src: url(../schriften/Exo-Bold.otf);
}
@font-face {
    font-family: “cracked-johnnie”;
    src: url(../schriften/cracked-johnnie.ttf);
}
#header {
    height: 100px;
    width: 100%;
    background-color: #F8FCF8;
    border-bottom: 2px black solid;
    opacity: 1;
    position: fixed;
    z-index: 2;
}
.logo {
    outline: none;
}
#logoimage {
    margin-top: -40px;
    top: 50%;
    position: relative;
    margin-left: 10px;
}
.footer {
    height: 40px;
    width: 100%;
    background-color: gray;
    position: relative;
    border-top: 2px black solid;
}
#box1 {
    height: 450px;
    padding: 50px;
    background-color: #871717;
    position: static;
    z-index: 1;
}
#box2 {
    height: 600px;
    padding-left: 50px;
    padding-right: 50px;
    background-color: #C5D637;
    position: static;
    z-index: 1;
}
#box3 {
    height: 600px;
    padding-left: 50px;
    padding-right: 50px;
    padding-bottom: 50px;
    background-color: #37B9D6;
    position: static;
    z-index: 1;
}
.buttons {
    width: 450px;
    margin-left: -225px;
    top: 70%;
    left: 50%;
    position: relative;
}
#infobutton {
    position: absolute;
    background-color: #F58C1F;
    border-radius: 5px;
    text-align: center;
    width: 280px;
    padding-top: 10px;
    padding-bottom: 10px;
    cursor: pointer;
    outline: none;
    -moz-user-select: none;
    -khtml-user-select: none;
    display: block;
    font-family: “Exo”, sans-serif;
    font-size: 1.4em;
    -webkit-transition: all .25s ease;
    -moz-transition: all .25s ease;
    -ms-transition: all .25s ease;
    -o-transition: all .25s ease;
    transition: all .25s ease;
}
#kontaktbutton {
    position: relative;
    margin-left: 30px;
    border: 3px #FFFFFF solid;
    border-radius: 5px;
    text-align: center;
    width: 140px;
    padding-top: 7px;
    padding-bottom: 7px;
    float: right;
    cursor: pointer;
    outline: none;
    -moz-user-select: none;
    -khtml-user-select: none;
    display: block;
    font-family: “Exo”, sans-serif;
    font-size: 1.4em;
    -webkit-transition: all .25s ease;
    -moz-transition: all .25s ease;
    -ms-transition: all .25s ease;
    -o-transition: all .25s ease;
    transition: all .25s ease;
}
#infobutton:hover {
    background-color: #409BF9;
    transition: all .25s ease-in-out;
    -moz-transition: all .25s ease-in-out;
    -webkit-transition: all .25s ease-in-out;
}
#kontaktbutton:hover {
    background-color: #409BF9;
    transition: all .25s ease-in-out;
    -moz-transition: all .25s ease-in-out;
    -webkit-transition: all .25s ease-in-out;
}
#navbutton {
    width: 50px;
    margin-left: -25px;
    left: 50%;
    padding-top: 5px;
    padding-bottom: 5px;
    text-align: center;
    border-left: 2px #FFFFFF solid;
    border-right: 2px #FFFFFF solid;
    border-bottom: 2px #FFFFFF solid;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
    position: relative;
    cursor: pointer;
    outline: none;
    z-index: 0;
    display: block;
}
.logotext {
    width: 500px;
    height: 100px;
    text-align: center;
    margin-left: -250px;
    margin-top: -50px;
    top: 40%;
    left: 50%;
    position: relative;
}
.text {
    font-family: “cracked-johnnie”, sans-serif;
    font-size: 5em;
    color: #FFFFFF;
    cursor: default;
    -moz-user-select: none;
    -khtml-user-select: none;
}
.text2 {
    font-family: “cracked-johnnie”, sans-serif;
    font-size: 5em;
    color: #F58C1F;
    cursor: default;
    -moz-user-select: none;
    -khtml-user-select: none;
}
.untertitel {
    color: #FFB160;
    font-family: “Exo”, sans-serif;
    margin: 0;
    font-size: 1.5em;
    cursor: default;
    -moz-user-select: none;
    -khtml-user-select: none;
}
.socialbox1 {
    height: 35px;
    width: 35px;
    margin-right: 30px;
    margin-top: -17.5px;
    top: 50%;
    position: relative;
    float: right;
    cursor: pointer;
}
.socialbox2 {
    height: 35px;
    width: 35px;
    margin-right: 20px;
    margin-top: -17.5px;
    top: 50%;
    position: relative;
    float: right;
    cursor: pointer;
}
.socialbox3 {
    height: 35px;
    width: 35px;
    margin-right: 20px;
    margin-top: -17.5px;
    top: 50%;
    position: relative;
    float: right;
    cursor: pointer;
}
.copyright {
    width: 100%;
    text-align: center;
    position: relative;
    padding-top: 8px;
    padding-bottom: 8px;
}
.dreieck {
    width: 0;
    height: 0;
    margin-left: 5px;
    border-left: 20px solid transparent;
    border-right: 20px solid transparent;
    border-bottom: 20px solid #FFFFFF;
    border-radius: 5px;
    position: relative;
}
#puffer {
    height: 50px;
    width: 100%;
    position: static;
    z-index: 0;
    margin-top: 400px;
}
#puffer2 {
    height: 50px;
    width: 100%;
    position: static;
    z-index: 0;
    margin-top: 518px;
}
</style>

app/views/home/_slider.html.erb
<div id="owl-demo">
  <div class="item"> <%= image_tag("pic1.jpg" , :id => "1")%></div>
  <div class="item"> <%= image_tag("pic2.jpg" , :id => "2")%> </div>
 <div class="item"><%= image_tag("pic3.jpg" , :id => "3")%> </div>
  <div class="item"> <%= image_tag("pic4.jpg" , :id => "4")%> </div>
  <div class="item"> <%= image_tag("pic5.jpg" , :id => "5")%></div>
  <div class="item"><%= image_tag("pic6.jpg" , :id => "6")%> </div>
  <div class="item"><%= image_tag("pic7.jpg" , :id => "7")%> </div>
  <div class="item"> <%= image_tag("pic8.jpg" , :id => "8")%> </div>
  <div class="item"> <%= image_tag("pic9.jpg" , :id => "9")%> </div>
  <div class="item"> <%= image_tag("pic10.jpg" , :id => "10")%> </div>
  <div class="item"> <%= image_tag("pic11.jpg" , :id => "11")%> </div>
  <div class="item"> <%= image_tag("pic12.jpg" , :id => "12")%> </div>
  <div class="item"> <%= image_tag("pic13.jpg" , :id => "13")%> </div>
  <div class="item"> <%= image_tag("pic14.jpg" , :id => "14")%> </div>
   
</div>
<script type="text/javascript">
    $(".owl-carousel").owlCarousel();
</script>

<style type="text/css">
    #owl-demo .item{
  margin: 3px;
  padding-top: 450px;
}
#owl-demo .item img{
  display: block;
  width: 100%;
  height: auto;
  
}
  
</style>
 <script type="text/javascript">
$(document).ready(function() {
 
  $("#owl-demo").owlCarousel({
 
      autoPlay: 2000, //Set AutoPlay to 3 seconds
 
      items : 3,
      itemsDesktop : [1199,3],
      itemsDesktopSmall : [979,3]
 
  });
 
});
 </script>

app/views/home/home.html.erb
<div id="header_nav"><%= image_tag("image.png" , :id => "1")%>
</div>
<!DOCTYPE html>
<html lang="en" >
    <head>
        <meta charset="utf-8" />
        <title>CSS3 Parallax scrolling slider | Script Tutorials</title>
        <link href="css/main.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <header tabindex="0">
            <h2>CSS3 Parallax scrolling slider</h2>
             
        </header>
 
        <div class="pss_main"> <!-- main parallax scrolling slider object -->
            <input id="r_1" type="radio" name="p" class="sel_page_1" checked="checked" /> <!-- hidden radios -->
            <input id="r_2" type="radio" name="p" class="sel_page_2" />
            <input id="r_3" type="radio" name="p" class="sel_page_3" />
            <input id="r_4" type="radio" name="p" class="sel_page_4" />

            <label for="r_1" class="pss_contr c1"></label> <!-- controls -->
            <label for="r_2" class="pss_contr c2"></label>
            <label for="r_3" class="pss_contr c3"></label>
            <label for="r_4" class="pss_contr c4"></label>

            <div class="pss_slides">
                <div class="pss_background"></div>
                <ul> <!-- slides -->
                    <li><%= image_tag("andhrameal.jpg" , :id => "1")%>
                        <div>ANDHRA MEALS</div>
                    </li>
                    <li><%= image_tag("biryani.JPG" , :id => "2")%>
                        <div>HYDRABADI DUM BIRYANI</br>(VEG & NON-VEG)</div>
                    </li>
                    <li><%= image_tag("curries.jpg" , :id => "3")%>
                        <div>CURRIES</br>(VEG & NON-VEG)</div>
                    </li>
                    <li><%= image_tag("pickles.jpg" , :id => "4")%>
                        <div>PICKLES</br>(AROUND NINE FLAVOURS)</div>
                    </li>
                </ul>
            </div>
        </div>
    </body>
</html>



<style type="text/css">
.pss_main {
    height:500px;
    position:relative;
    width:100%;
}
.pss_main input {
    display:none;
}
.pss_contr {
    background:#E0371E url(../images/up.png) no-repeat center center;
    cursor:pointer;
    display:none;
    height:70px;
    left:50%;
    opacity:0.3;
    position:absolute;
    top:5%;
    width:70px;
    z-index:2;

    /* css3 transition */
    -webkit-transition:opacity linear 0.3s;
    -moz-transition:opacity linear 0.3s;
    -o-transition:opacity linear 0.3s;
    -ms-transition:opacity linear 0.3s;
    transition:opacity linear 0.3s;
    border-radius:50% 50% 50% 50%;
    box-shadow:0 1px 2px #AF2C19 inset;
}
.pss_contr:hover {
    opacity:1;
}
.sel_page_1:checked ~ .pss_contr.c2, .sel_page_2:checked ~ .pss_contr.c3,
.sel_page_3:checked ~ .pss_contr.c4 {
    background-image:url(../images/down.png);
    display:block;
    top:85%;
}
.sel_page_2:checked ~ .pss_contr.c1, .sel_page_3:checked ~ .pss_contr.c2,
.sel_page_4:checked ~ .pss_contr.c3  {
    background-image:url(../images/up.png);
    display:block;
}
.pss_slides {
    height:100%;
    overflow:hidden;
    position:relative;
}
.pss_background {
    background:url(../images/bg.png) no-repeat scroll 0 0;
    height:100%;
    left:0;
    overflow:hidden;
    position:absolute;
    top:0;
    width:100%;

    /* css3 background-size */
    -webkit-background-size:cover;
    -moz-background-size:cover;
    -o-background-size:cover;
    -ms-background-size:cover;
    background-size:cover;
}
.pss_main input:checked ~ .pss_slides {
    /* css3 transition */
    -webkit-transition:all linear 1.0s;
    -moz-transition:all linear 1.0s;
    -o-transition:all linear 1.0s;
    -ms-transition:all linear 1.0s;
    transition:all linear 1.0s;
}
.sel_page_1:checked ~ .pss_slides {
    background-color: ;
}
.sel_page_2:checked ~ .pss_slides {
    background-color: ;
}
.sel_page_3:checked ~ .pss_slides {
    background-color:;
}
.sel_page_4:checked ~ .pss_slides {
    background-color: ;
}
.pss_main input:checked ~ .pss_slides .pss_background {
    /* css3 transition */
    -webkit-transition:all linear 1.5s;
    -moz-transition:all linear 1.5s;
    -o-transition:all linear 1.5s;
    -ms-transition:all linear 1.5s;
    transition:all linear 1.5s;
}
.sel_page_1:checked ~ .pss_slides .pss_background {
    background-position:0 0;
}
.sel_page_2:checked ~ .pss_slides .pss_background {
    background-position:0 -500px;
}
.sel_page_3:checked ~ .pss_slides .pss_background {
    background-position:0 -1000px;
}
.sel_page_4:checked ~ .pss_slides .pss_background {
    background-position:0 -1500px;
}
.pss_slides ul {
    height:100%;
    list-style:none;
    position:relative;
    top:0;

    /* css3 transition */
    -webkit-transition:top ease-in 1.0s;
    -moz-transition:top ease-in 1.0s;
    -o-transition:top ease-in 1.0s;
    -ms-transition:top ease-in 1.0s;
    transition:top ease-in 1.0s; 
}
.pss_slides ul  li {
    height:100%;
    opacity:0.1;
    position:relative;
    text-align:center;

    /* css3 transition */
    -webkit-transition:opacity ease-in 1.0s;
    -moz-transition:opacity ease-in 1.0s;
    -o-transition:opacity ease-in 1.0s;
    -ms-transition:opacity ease-in 1.0s;
    transition:opacity ease-in 1.0s; 
}
.sel_page_1:checked ~ .pss_slides ul li:first-child,
.sel_page_2:checked ~ .pss_slides ul li:nth-child(2),
.sel_page_3:checked ~ .pss_slides ul li:nth-child(3),
.sel_page_4:checked ~ .pss_slides ul li:nth-child(4) {
    opacity:1;
}
.pss_slides ul li img{
    display:block;
    margin:0 auto;
    padding:40px;
}
.pss_slides ul li div{
    background-color:#000000;
    border-radius:10px 10px 10px 10px;
    box-shadow:0 0 5px #FFFFFF inset;
    color:#FFFFFF;
    font-size:26px;
    left:-20%;
    margin:0 auto;
    padding:20px;
    position:absolute;
    top:50%;
    width:200px;

    /* css3 transition */
    -webkit-transition:left ease-in 1.0s;
    -moz-transition:left ease-in 1.0s;
    -o-transition:left ease-in 1.0s;
    -ms-transition:left ease-in 1.0s;
    transition:left ease-in 1.0s; 
}
.sel_page_1:checked ~ .pss_slides ul {
    top:0;
}
.sel_page_2:checked ~ .pss_slides ul {
    top:-100%;
}
.sel_page_3:checked ~ .pss_slides ul {
    top:-200%;
}
.sel_page_4:checked ~ .pss_slides ul {
    top:-300%;
}
.sel_page_1:checked ~ .pss_slides ul li:first-child div,
.sel_page_2:checked ~ .pss_slides ul li:nth-child(2) div,
.sel_page_3:checked ~ .pss_slides ul li:nth-child(3) div,
.sel_page_4:checked ~ .pss_slides ul li:nth-child(4) div {
    left:10%;
}

	body {
     
    width:100%;
    background-color:#F0F0F0;
}

#header_nav {
    width:500px;
    height:100px;
    background-color:#666;
    position:fixed;
    top:0;
    left:0;
}
#header_nav img {
    height:100%;
}
	 </style>
	 <script type="text/javascript">
     $(function(){
    $('#header_nav').data('size','big');
});

$(window).scroll(function(){
    if($(document).scrollTop() > 0)
    {
        if($('#header_nav').data('size') == 'big')
        {
            $('#header_nav').data('size','small');
            $('#header_nav').stop().animate({
                height:'40px'
            },600);
        }
    }
    else
    {
        if($('#header_nav').data('size') == 'small')
        {
            $('#header_nav').data('size','big');
            $('#header_nav').stop().animate({
                height:'100px'
            },600);
        }  
    }
}); 
	 </script>

app/views/home/special.html.erb
<div id="title" class="slide header" >
  <h1>CURRIES & PICKLES</h1> 
  <%= render 'slider' %>
</div>

<div id="slide1" class="slide">
  <div class="title" >
    <h1>** ABOUT US **</h1> 
• WE BANGALORE BASED M/S NAMED AS CURRIES & 
PICKLES HAVE CHAIN OF RESTAURENTS WITH HOME 
DELIVERY AND OUT­DOOR CATERING SERVICE</br>
• OUR DELICIOUS VEG & NON­VEG CURRIES HAS ALL 
ANDHRA­SPECILITIES.</br>
• WE PROVIDE ALL SOUTH­INDIAN AND NORTH­INDIAN  
DISHES TOO.</br>
• TO ENJOY THE REAL TASTE OF HYDRABADI­DUM­
BIRYANI (COOKED­IN­FIREWOOD) VISIT OUR CURRIES 
& PICKLES .</br>
• WE PREPARE VEG & NON­VEG ITEMS SEPARATELY TO 
MAINTAIN THE ESSENCE OF TASTE.</br>
• WE PROVIDE OUTDOOR CATERING ALL OVER 
BANGALORE ..</br>
• WE SPECIALISTS IN HYDRABADI­DUM BIRYANI AND 
ANDHRA­SPECIAL CURRIES..</br>
• WE DO PROVIDE DELICIOUS NORTH­INDIAN AND 
PUNJABI STYLE DISHES TOO .</br>
• WE ACCEPT BULK ORDERS FOR  BIRYANI, 
CHAPATI,PULKAS AND ANY TANDOORI ITEMS.</br>
• WE PROVIDE DAILY CATERING FOR CORPORATES AND 
OTHER OFFICIALS COMPANIES.</br>
• IN BANGALORE TOTAL 7 CURRY POINT OUTLETS AND 2 
RESTAURENTS ARE AT YOUR SERVICE WITH EXCELLENT 
QUALITY OF FOOD.</br>


 
</p>
  </div>

</div>

<div id="slide2" class="slide">
  <div class="title" align="right">
    <h1 >**LOCATIONS**</h1>
     KAGGADASA­PURA</br>
     MARATHA­HALLI</br>
     BELLANDUR</br>
     RAJAJINAGAR(*NEW*)

  </div>
     
    <%= image_tag("pic3.jpg" , :id => "1")%>
</div>

<div id="slide3" class="slide">
  <div class="title">
    <h1>** CONTACT **</h1>
     V.NAVEEN KUMAR</br>
     CALL:+919632196146</br>
          +919538181222</br> 
          +918123490170</br>
     MAIL US AT : naveenkumar4urs@gmail.com</br>
                  currysnpickles@gmail.com</br>

     
  </div>
</div>

<!-- <div id="slide4" class="slide header">
    
</div> --><div id="header-colors"></div>  
<style type="text/css">
    @import url(http://fonts.googleapis.com/css?family=Nunito);

html {
  height: 100%;
  overflow: hidden;
}

body { 
  margin:0;
  padding:0;
    perspective: 1px;
    transform-style: preserve-3d;
  height: 100%;
  overflow-y: scroll;
  overflow-x: hidden;
  font-family: Nunito;
}

h1 {
   font-size: 250%
}

p {
  font-size: 140%;
  line-height: 150%;
  color: #333;
}

.slide {
  position: relative;
  padding: 25vh 10%;
  min-height: 100vh;
  width: 100vw;
  box-sizing: border-box;
  box-shadow: 0 -1px 10px rgba(0, 0, 0, .7);
    transform-style: inherit;
}

img {
  position: absolute;
  top: 50%;
  left: 35%;
  width: 320px;
  height: 240px;
  transform: translateZ(.25px) scale(.75) translateX(-94%) translateY(-100%) rotate(2deg);
  padding: 10px;
  border-radius: 5px;
  background: rgba(240,230,220, .7);
  box-shadow: 0 0 8px rgba(0, 0, 0, .7);
}

img:last-of-type {
  transform: translateZ(.4px) scale(.6) translateX(-104%) translateY(-40%) rotate(-5deg);
}

.slide:before {
  content: "";
  position: absolute;
  top: 0;
  bottom: 0;
  left:0;
  right:0;
}

.title {
  width: 50%;
  padding: 5%;
  border-radius: 5px;
  background: rgba(240,230,220, .7);
  box-shadow: 0 0 8px rgba(0, 0, 0, .7);
}

.slide:nth-child(2n) .title {
  margin-left: 0;
  margin-right: auto;
}

.slide:nth-child(2n+1) .title {
  margin-left: auto;
  margin-right: 0;
}

.slide, .slide:before {
  background: 50% 50% / cover;  
}

.header {
  text-align: center;
  font-size: 175%;
  color: #fff;
  text-shadow: 0 2px 2px #000;
}

#title {
  background-image: url("http://lorempixel.com/output/abstract-q-c-640-480-6.jpg");
   background-attachment: fixed;  
}

#slide1:before {
  background-image: url("http://lorempixel.com/output/abstract-q-c-640-480-4.jpg");
  transform: translateZ(-1px) scale(2);
  z-index:-1;
}

#slide2 {
  background-image: url("http://lorempixel.com/output/abstract-q-c-640-480-3.jpg");
  background-attachment: fixed;
}

#slide3:before {
  background-image: url("http://lorempixel.com/output/abstract-q-c-640-480-5.jpg");
  transform: translateZ(-1px) scale(2);
  z-index:-1;
}

#slide4 {
  background: #222;
}
</style>>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CURRIES & PICKLES</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div style="background-color:red ;padding-top:15px;"><header align="center"><%= link_to "ABOUT US",special_path %>
 </br><%= link_to "HOME",root_path %></header></div> 
<div><footer>@raghu</footer></div>    
<%= yield %>
<body style="background-color:black ;"> 

</body>
</html>